{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<font size=6 color=red>30 días de Python: Día 22 - Tipos de errores de Python</font>\n",
    "\n",
    "---\n",
    "\n",
    "## Tipos de errores de Python\n",
    "\n",
    "Cuando escribimos código, es común que cometamos un error tipográfico o algún otro error común. Si nuestro código no se ejecuta, el intérprete de Python mostrará un mensaje que contiene comentarios con información sobre dónde ocurre el problema y el tipo de error.\n",
    "\n",
    "A veces también nos da sugerencias sobre una posible solución. Comprender los diferentes tipos de errores en los lenguajes de programación nos ayudará a depurar nuestro código rápidamente y también nos hará mejores en lo que hacemos.\n",
    "\n",
    "Veamos los tipos de error más comunes uno por uno. Primero, abramos nuestro shell interactivo de Python. Vaya a la terminal de su computadora y escriba 'python'. Se abrirá el shell interactivo de python.\n",
    "\n",
    "---\n",
    "\n",
    "# Error de sintaxis\n",
    "\n",
    "*Ejemplo 1: Error de sintaxis*\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> print 'hello world'\n",
    "  File \"<stdin>\", line 1\n",
    "    print 'hello world'\n",
    "                      ^\n",
    "SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello world')?\n",
    ">>>\n",
    "```\n",
    "\n",
    "Como puede ver, cometimos un error de sintaxis porque olvidamos encerrar la cadena entre paréntesis y Python ya sugiere la solución. \n",
    "Arreglemoslo.\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> print 'hello world'\n",
    "  File \"<stdin>\", line 1\n",
    "    print 'hello world'\n",
    "                      ^\n",
    "SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello world')?\n",
    ">>> print('hello world')\n",
    "hello world\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> print 'hello world'\n",
    "  File \"<stdin>\", line 1\n",
    "    print 'hello world'\n",
    "                      ^\n",
    "SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello world')?\n",
    ">>> print('hello world')\n",
    "hello world\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "El error fue un SyntaxError. Después de la corrección, nuestro código se ejecutó sin problemas. Veamos más tipos de errores.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Error de nombre\n",
    "\n",
    "*Ejemplo 1: Error de nombre*\n",
    "\n",
    "```bash\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> print(age)\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "NameError: name 'age' is not defined\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "\n",
    "Como puede ver en el mensaje anterior, la edad del nombre no está definida. Sí, es cierto que no definimos una variable de edad pero intentábamos imprimirla como si la hubiéramos declarado. Ahora, arreglemos esto declarándolo y asignándole un valor.\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> print(age)\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "NameError: name 'age' is not defined\n",
    ">>> age = 25\n",
    ">>> print(age)\n",
    "25\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "El tipo de error fue NameError. Depuramos el error definiendo el nombre de la variable.\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## IndexError\n",
    "\n",
    "*Ejemplo 1: Error de índice*\n",
    "\n",
    "```bash\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> numbers = [1, 2, 3, 4, 5]\n",
    ">>> numbers[5]\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "IndexError: list index out of range\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "\n",
    "En el ejemplo anterior, Python generó un IndexError porque la lista solo tiene índices del 0 al 4, por lo que estaba fuera de rango.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Error de módulo no encontrado\n",
    "\n",
    "*Ejemplo 1: ModuleNotFoundError*\n",
    "\n",
    "```bash\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> import maths\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ModuleNotFoundError: No module named 'maths'\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "\n",
    "En el ejemplo anterior, agregué una s adicional a las matemáticas deliberadamente y se generó ModuleNotFoundError. \n",
    "Vamos a solucionarlo eliminando las s adicionales de las matemáticas.\n",
    "\n",
    "```bash\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> import maths\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ModuleNotFoundError: No module named 'maths'\n",
    ">>> import math\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "\n",
    "Lo arreglamos, así que usemos algunas de las funciones del módulo matemático.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Error de atributo\n",
    "\n",
    "*Ejemplo 1: Error de atributo*\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> import maths\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ModuleNotFoundError: No module named 'maths'\n",
    ">>> import math\n",
    ">>> math.PI\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "AttributeError: module 'math' has no attribute 'PI'\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "Como puedes ver, ¡he vuelto a cometer un error! En lugar de pi, traté de llamar a una función PI desde el módulo matemático. \n",
    "Levantó un error de atributo, es decir, que la función no existe en el módulo. Arreglemoslo cambiando de PI a pi.\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> import maths\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ModuleNotFoundError: No module named 'maths'\n",
    ">>> import math\n",
    ">>> math.PI\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "AttributeError: module 'math' has no attribute 'PI'\n",
    ">>> math.pi\n",
    "3.141592653589793\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "Ahora, cuando llamamos a pi desde el módulo matemático, obtuvimos el resultado.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Error de clave\n",
    "\n",
    "*Ejemplo 1: Error de clave*\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> users = {'name':'Asab', 'age':250, 'country':'Finland'}\n",
    ">>> users['name']\n",
    "'Asab'\n",
    ">>> users['county']\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "KeyError: 'county'\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "Como puede ver, hubo un error tipográfico en la clave utilizada para obtener el valor del diccionario. entonces, este es un error clave y la solución es bastante sencilla. ¡Hagámoslo!\n",
    "\n",
    "Depuramos el error, nuestro código se ejecutó y obtuvimos el valor.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Error de tecleado\n",
    "\n",
    "*Ejemplo 1: Error de tipo*\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> 4 + '3'\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "TypeError: unsupported operand type(s) for +: 'int' and 'str'\n",
    ">>>\n",
    "\n",
    " ```\n",
    "\n",
    "En el ejemplo anterior, se genera un TypeError porque no podemos agregar un número a una cadena. La primera solución sería convertir la cadena a int o float. Otra solución sería convertir el número en una cadena (el resultado sería '43').\n",
    "\n",
    "Sigamos la primera corrección.\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> 4 + '3'\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "TypeError: unsupported operand type(s) for +: 'int' and 'str'\n",
    ">>> 4 + int('3')\n",
    "7\n",
    ">>> 4 + float('3')\n",
    "7.0\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "Se eliminó el error y obtuvimos el resultado que esperábamos.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## ImportError\n",
    "\n",
    "*Ejemplo 1: Error de tipo*\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> from math import power\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ImportError: cannot import name 'power' from 'math'\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "No hay una función llamada power en el módulo matemático, tiene un nombre diferente: pow. Vamos a corregirlo:\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> from math import power\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ImportError: cannot import name 'power' from 'math'\n",
    ">>> from math import pow\n",
    ">>> pow(2,3)\n",
    "8.0\n",
    ">>>\n",
    "\n",
    "```\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## ValorError\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> int('12a')\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ValueError: invalid literal for int() with base 10: '12a'\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "En este caso, no podemos cambiar la cadena dada a un número, debido a la letra 'a' que contiene.\n",
    "\n",
    "---\n",
    "\n",
    "## Error de división cero\n",
    "\n",
    "```python\n",
    "> python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> 1/0\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ZeroDivisionError: division by zero\n",
    ">>>\n",
    "\n",
    "```\n",
    "\n",
    "No podemos dividir un número por cero.\n",
    "\n",
    "Hemos cubierto algunos de los tipos de error de python, si desea obtener más información al respecto, consulte la documentación de python sobre los tipos de error de python. Si es bueno para leer los tipos de errores, podrá corregirlos rápidamente y también se convertirá en un mejor programador."
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
